#This file is developed by Team 11 of COMP90024 of The University of Melbourne, under Apache Licence(see LICENCE).
#Researched Cities: Victoria, AU
#Team member - id:
#Zhijia Lu         921715
#Jing Du           775074
#Chenyang Lu       951933
#Pengcheng Yao     886326
#Echo Gu           520042

- name: mkdir repo
  raw: mkdir -p /opt/workspace/analyzer2

- name: git code
  git:
    repo: 'https://zhijial@bitbucket.org/zhijial/vuc-prediction-analyzer2_final.git'
    dest: /opt/workspace/analyzer2
    clone: yes

- name: build analyzer2 container
  raw: cd /opt/workspace/analyzer2; docker build -t analyzer2 .; sleep 5

- name: run analyzer2 container
  raw: docker run -d --net=host analyzer2