#This file is developed by Team 11 of COMP90024 of The University of Melbourne, under Apache Licence(see LICENCE).
#Researched Cities: Victoria, AU
#Team member - id:
#Zhijia Lu         921715
#Jing Du           775074
#Chenyang Lu       951933
#Pengcheng Yao     886326
#Echo Gu           520042

- name: mkdir repo
  raw: mkdir -p /opt/workspace/crawler3

- name: git code
  git:
    repo: 'https://zhijial@bitbucket.org/zhijial/vuc-prediction-crawler3_final.git'
    dest: /opt/workspace/crawler3
    clone: yes

- name: build service2 container
  raw: cd /opt/workspace/crawler3; docker build -t crawler3.; sleep 5

- name: run service1 container
  raw: docker run -d --net=host crawler3