version: "3"
services:

  couch_master:
    image: "couchdb:2.3.0"
    restart: always
    network_mode: host
    ports:
      - "5984:5984"
      - "5986:5986"
      - "4369:4369"
      - "9100-9200:9100-9200"
    volumes:
      - /home/ubuntu/couchdb/master/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=pass
      - NODENAME=172.26.38.189
    container_name: couch_node