#This file is developed by Team 11 of COMP90024 of The University of Melbourne, under Apache Licence(see LICENCE).
#Researched Cities: Victoria, AU
#Team member - id:
#Zhijia Lu         921715
#Jing Du           775074
#Chenyang Lu       951933
#Pengcheng Yao     886326
#Echo Gu           520042

#Instance dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update;sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest
# pip install openstacksdk