#This file is developed by Team 11 of COMP90024 of The University of Melbourne, under Apache Licence(see LICENCE).
#Researched Cities: Victoria, AU
#Team member - id:
#Zhijia Lu         921715
#Jing Du           775074
#Chenyang Lu       951933
#Pengcheng Yao     886326
#Echo Gu           520042

# Common vars
availability_zone: melbourne-qh2-uom

#volume
# volumes:
#   - vol_name: Webserver
#     vol_size: 10
#   - vol_name: CouchDB1
#     vol_size: 80
#   - vol_name: CouchDB2
#     vol_size: 80
#   - vol_name: CouchDB3
#     vol_size: 80

#Securiity group
security_groups:
  - name: Team11_SSH
    description: "CCC ASS2 security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: Team11_HTTP
    description: "CCC ASS2 security group for HTTP access"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: Team11_icmp
    description: "CCC ASS2 security group for Ping"
    protocol: icmp
    port_range_min: 0
    port_range_max: 255
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: Team11_couchdb
    description: "CCC ASS2 security group for couchdb (tcp)"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: Team11_backend
    description: "CCC ASS2 security group for backend"
    protocol: tcp
    port_range_min: 8080
    port_range_max: 8080
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16
  - name: Team11_website
    description: "CCC ASS2 security group for website"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0
    # remote_ip_prefix: 128.250.0.0/16